### ISSUE TITLE
Facilitate flat, implicit folder structure with init.py files

### ISSUE THREAD

**Issue by thaije** [matrxs/MATRXS#94]
B: Flat, but implicit. 
```
From matrxs.agents import AgentBrain 
From matrxs.objects import EnvObject 
From matrxs.tasks.bw4t import BW4TAgent
```

For example: 
https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/cross_decomposition/__init__.py

**Comment by mlstolk** [comment]
**Encountered a problem.**

Partially working (actions, agents, capabilities, done), but stuck on flattening the **objects** sub-package.

matrx\objects\__init.py__  imports:
```
from .simple_objects import *
from .advanced_objects import *
from .agent_body import *
from .env_object import *

```
When both simple_objects and advanced_objects are included in __init.py__, the latter of the two fails at compile time; apparently because of multiple imports of env_object. 
The order of the first two import lines of __init.py__ determines in which of the files the import of env_object fails.
